<a href="https://colab.research.google.com/github/zeelrupapara/Machine-Learning-Models/blob/main/Data_Pre-processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [ ]:
dataset = pd.read_csv("Data.csv")
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

# Take care of missing data

In [ ]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])
X[:, 1:3]

array([[44.0, 72000.0],
       [27.0, 48000.0],
       [30.0, 54000.0],
       [38.0, 61000.0],
       [40.0, 63777.77777777778],
       [35.0, 58000.0],
       [38.77777777777778, 52000.0],
       [48.0, 79000.0],
       [50.0, 83000.0],
       [37.0, 67000.0]], dtype=object)

# Encoding categorical data

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [0])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))
X

array([[0.0, 1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [0.0, 1.0, 0.0, 0.0, 35.0, 58000.0],
       [1.0, 0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [0.0, 1.0, 0.0, 0.0, 48.0, 79000.0],
       [1.0, 0.0, 1.0, 0.0, 50.0, 83000.0],
       [0.0, 1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder


le = LabelEncoder()
y = le.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

# StanderdScaler

In [ ]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X = sc.fit_transform(X[:, 3:])
X

array([[-6.54653671e-01,  7.58874362e-01,  7.49473254e-01],
       [ 1.52752523e+00, -1.71150388e+00, -1.43817841e+00],
       [-6.54653671e-01, -1.27555478e+00, -8.91265492e-01],
       [ 1.52752523e+00, -1.13023841e-01, -2.53200424e-01],
       [-6.54653671e-01,  1.77608893e-01,  6.63219199e-16],
       [-6.54653671e-01, -5.48972942e-01, -5.26656882e-01],
       [ 1.52752523e+00,  0.00000000e+00, -1.07356980e+00],
       [-6.54653671e-01,  1.34013983e+00,  1.38753832e+00],
       [-6.54653671e-01,  1.63077256e+00,  1.75214693e+00],
       [-6.54653671e-01, -2.58340208e-01,  2.93712492e-01]])

# **PART 2**

In [12]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

dataset1 = pd.read_csv("Data.csv")
X = dataset1.iloc[:, :-1].values
y = dataset1.iloc[:, -1].values

from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [0])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)

# Rescale data

In [9]:
from sklearn.preprocessing import MinMaxScaler
 
avgscaler = MinMaxScaler(feature_range = (0, 1))
X = avgscaler.fit_transform(X)
X

array([[1.        , 0.        , 0.        , 0.73913043, 0.68571429],
       [0.        , 0.        , 1.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        , 0.13043478, 0.17142857],
       [0.        , 0.        , 1.        , 0.47826087, 0.37142857],
       [0.        , 1.        , 0.        , 0.56521739, 0.45079365],
       [1.        , 0.        , 0.        , 0.34782609, 0.28571429],
       [0.        , 0.        , 1.        , 0.51207729, 0.11428571],
       [1.        , 0.        , 0.        , 0.91304348, 0.88571429],
       [0.        , 1.        , 0.        , 1.        , 1.        ],
       [1.        , 0.        , 0.        , 0.43478261, 0.54285714]])

# Binarize Data (Make Binary)  

In [13]:
from sklearn.preprocessing import Binarizer

binarizer = Binarizer(threshold = 0.0).fit(X)
binaryX = binarizer.transform(X)
np.set_printoptions(precision = 3)
binaryX

array([[1., 0., 0., 1., 1.],
       [0., 0., 1., 1., 1.],
       [0., 1., 0., 1., 1.],
       [0., 0., 1., 1., 1.],
       [0., 1., 0., 1., 1.],
       [1., 0., 0., 1., 1.],
       [0., 0., 1., 1., 1.],
       [1., 0., 0., 1., 1.],
       [0., 1., 0., 1., 1.],
       [1., 0., 0., 1., 1.]])

# Standardize Data  (Feature Scaling)

In [16]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
rescaledX = scaler.fit_transform(X)
rescaledX

array([[ 1.225e+00, -6.547e-01, -6.547e-01,  7.589e-01,  7.495e-01],
       [-8.165e-01, -6.547e-01,  1.528e+00, -1.712e+00, -1.438e+00],
       [-8.165e-01,  1.528e+00, -6.547e-01, -1.276e+00, -8.913e-01],
       [-8.165e-01, -6.547e-01,  1.528e+00, -1.130e-01, -2.532e-01],
       [-8.165e-01,  1.528e+00, -6.547e-01,  1.776e-01,  6.632e-16],
       [ 1.225e+00, -6.547e-01, -6.547e-01, -5.490e-01, -5.267e-01],
       [-8.165e-01, -6.547e-01,  1.528e+00,  0.000e+00, -1.074e+00],
       [ 1.225e+00, -6.547e-01, -6.547e-01,  1.340e+00,  1.388e+00],
       [-8.165e-01,  1.528e+00, -6.547e-01,  1.631e+00,  1.752e+00],
       [ 1.225e+00, -6.547e-01, -6.547e-01, -2.583e-01,  2.937e-01]])